"""Typed models for the PixieChess API.

Pydantic v2 models with camelCase wire aliasing — field names are
``snake_case`` in Python, ``camelCase`` on the wire.
"""

from .auctions import (
    Auction,
    AuctionDaySummary,
    AuctionMetadata,
    AuctionPieceInfo,
    CompletedDaySummary,
    DailyVolume,
    InstantMintPrice,
    PastAuction,
    PastAuctionEntry,
    PastAuctionsPage,
    PastDayBucket,
    Prices,
    SalesStats,
    VrgdaPrice,
)
from .common import CamelModel, Helmet, PlayerInfo, ResponseMeta, SuggestSignup
from .game import Game, GameEnding, GameResult, RatingChange
from .leaderboard import (
    LeaderboardEntry,
    LeaderboardPage,
    LeaderboardStats,
    PointsLeaderboardCurrentUser,
    PointsLeaderboardEntry,
    PointsLeaderboardPage,
)
from .misc import EthUsdPrice, LiveFeedEvent, PublicConfig
from .pieces import (
    BurnedInfo,
    BurnedTournament,
    Piece,
    PieceAttribute,
    PieceMetadata,
    PiecesPage,
)
from .tournaments import (
    BurnRuleset,
    GameplayRuleset,
    GameTiming,
    GameTimingPlayer,
    MatchupEntry,
    MatchupSource,
    NotificationStatus,
    PayoutSplit,
    SourceMatches,
    SubstitutionRule,
    Tournament,
    TournamentColors,
    TournamentDetails,
    TournamentImages,
    TournamentList,
    TournamentRuleset,
    TournamentUserInfo,
    WaitlistEntry,
)
from .user import (
    ColorRecord,
    MatchHistoryEntry,
    MatchHistoryPage,
    MatchTiming,
    User,
)

__all__ = [
    "Auction",
    "AuctionDaySummary",
    "AuctionMetadata",
    "AuctionPieceInfo",
    "BurnRuleset",
    "BurnedInfo",
    "BurnedTournament",
    "CamelModel",
    "ColorRecord",
    "CompletedDaySummary",
    "DailyVolume",
    "EthUsdPrice",
    "Game",
    "GameEnding",
    "GameResult",
    "GameTiming",
    "GameTimingPlayer",
    "GameplayRuleset",
    "Helmet",
    "InstantMintPrice",
    "LeaderboardEntry",
    "LeaderboardPage",
    "LeaderboardStats",
    "LiveFeedEvent",
    "MatchHistoryEntry",
    "MatchHistoryPage",
    "MatchTiming",
    "MatchupEntry",
    "MatchupSource",
    "NotificationStatus",
    "PastAuction",
    "PastAuctionEntry",
    "PastAuctionsPage",
    "PastDayBucket",
    "PayoutSplit",
    "Piece",
    "PieceAttribute",
    "PieceMetadata",
    "PiecesPage",
    "PlayerInfo",
    "PointsLeaderboardCurrentUser",
    "PointsLeaderboardEntry",
    "PointsLeaderboardPage",
    "Prices",
    "PublicConfig",
    "RatingChange",
    "ResponseMeta",
    "SalesStats",
    "SourceMatches",
    "SubstitutionRule",
    "SuggestSignup",
    "Tournament",
    "TournamentColors",
    "TournamentDetails",
    "TournamentImages",
    "TournamentList",
    "TournamentRuleset",
    "TournamentUserInfo",
    "User",
    "VrgdaPrice",
    "WaitlistEntry",
]
